
input:
  cache_path: "./cache"


weather:
  cache_path: "./cache/pred_cache.pkl"

# config/settings.yaml
output:
  # Directory settings
  base_dir: "./results"  # All outputs go under this root
  subdirs:
    plots: "plots/{species}/{date}"  # Dynamic paths
    reports: "reports"
    json: "json_data"
  
  # Plot configuration
  plots:
    map:
      style: "seaborn-darkgrid"
      cmap: "viridis"
      dpi: 300
      formats: ["png", "pdf"]
    timeseries:
      figsize: [10, 6]
      rolling_mean: 7  # days
    
  # Report generation
  report:
    template: "templates/report.html"
    default_variables: ["F1", "F2", "F3"]
    summary_stats: ["mean", "min", "max"]
  
  # Data export
  data:
    json:
      indent: 2
      float_precision: 3
    netcdf:
      compression: True
      compression_level: 4
  
  # Notification settings
  notifications:
    email:
      enabled: False
      recipients: []
    logfile: "output_log.txt"